// wire-protocol/schema.cue
//
// Schema for ADR-WIRE-01: the port wire protocol Liminara's
// `Liminara.Executor.Port` exchanges with Python ops over stdio.
//
// This schema freezes the JSON-over-{packet,4} message shapes the
// runtime exchanges today. It does not change runtime semantics. It is
// schema-freezing only.
//
// Source-of-truth bindings (live runtime):
//   - runtime/apps/liminara_core/lib/liminara/executor/port.ex
//     (encode_request/3, decode_response/1, normalize_success/1)
//   - runtime/python/src/liminara_op_runner.py
//     (read_message, write_message, handle_request)
//   - runtime/apps/liminara_core/lib/liminara/run.ex (warning_payload/1
//     at line 710 — the string-keyed JSON shape warnings take on the
//     wire, divergent from Liminara.Warning's atom-keyed Elixir struct).
//
// Wire convention recap (per D-2026-04-20-026 + M-WARN-04 fix):
//   - All keys are strings on the wire (JSON, not Elixir atoms).
//   - Atom values are stringified (e.g. severity :degraded → "degraded")
//     by warning_payload/1 before serialization. Schema disjunctions
//     mirror that stringified taxonomy. No regex `=~` patterns.
//   - Nilable Elixir fields are omitted from the JSON object rather
//     than serialized as JSON null where the runtime side enforces no
//     null. Schema represents these as optional `?:` keys.
//
// Bundled per-fixture entry shape: each fixture pairs a request and
// its corresponding response in a single document so the contract is
// end-to-end legible per fixture (D-2026-04-26-036 convention 1).

package wireprotocol

// schema_version is fixed at the cohort version. Bumping the cohort
// (v1.0.0 → v1.1.0 additive, → v2.0.0 breaking) is governed by
// ADR-EVOLUTION-01 (M-CONTRACT-04) when it lands.
schema_version: "1.0.0"

// ─── Top-level fixture entry: one request + one response ───────────
//
// Each fixture under fixtures/v1.0.0/ unifies with #Exchange.
// The `request.id` and `response.id` MUST match — that's the
// correlation invariant `Liminara.Executor.Port.receive_response/2`
// (port.ex:140) enforces.

#Exchange: close({
	request:  #Request
	response: #Response

	// Cross-field invariant: request and response correlate by `id`.
	// Mirrors the receive_response/2 loop that ignores responses with
	// non-matching IDs (port.ex:147 — `{:ok, _wrong_id}` continues
	// waiting).
	request: id:  string
	response: id: request.id
})

// ─── Request ───────────────────────────────────────────────────────
//
// Mirrors encode_request/3 in port.ex:65–85. Required keys: `id`,
// `op`, `inputs`. Optional `context` is added by Map.put/3 only when
// the caller supplies an %ExecutionContext{} (port.ex:74–79); when
// `context` is absent the key is omitted from the JSON object
// entirely.

#Request: close({
	// Correlation ID. Generated by generate_id/0 (port.ex:201) — 16
	// lowercase hex characters from 8 random bytes via base32. The
	// schema admits any non-empty string; the runtime owns generation.
	id: string & !=""

	// Op-module name to dispatch. Python side uses
	// `importlib.import_module(f"ops.{op_name}")` — a missing or
	// empty value triggers an error response (op_runner.py:60–61).
	op: string & !=""

	// Op-specific input payload. Free-form key→value map; per-op
	// content shape is the op's concern, not this contract's.
	// Per-content-type schemas are out of scope here (ADR-CONTENT-01,
	// M-CONTRACT-04, owns the namespace).
	inputs: {[string]: _}

	// Optional ExecutionContext from M-RUN-01. When present, riders
	// are passed straight through to the op via `context` (matching
	// the Python runner's handle_request msg.get("context") at
	// op_runner.py:58). Shape mirrors Liminara.ExecutionContext —
	// fields with nil values may be omitted or serialized as null;
	// downstream consumers tolerate either.
	context?: #ExecutionContext
})

#ExecutionContext: close({
	run_id?:           string | null
	started_at?:       string | null
	pack_id?:          string | null
	pack_version?:     string | null
	replay_of_run_id?: string | null
	topic_id?:         string | null
})

// ─── Response ──────────────────────────────────────────────────────
//
// The response is one of two disjoint shapes, discriminated by
// `status`:
//
//   - "ok" — success; `outputs` is required, `decisions` and
//     `warnings` are optional and may be omitted entirely. `error`
//     MUST NOT appear.
//   - "error" — failure; `error` is required (a free-form message
//     string). `outputs`, `decisions`, `warnings` MUST NOT appear.
//
// The two shapes are mutually exclusive — a response with both
// `outputs` and `error` violates the schema (port.ex:50–55 pattern-
// matches on status alone and would silently pick the success
// branch; the schema makes the violation explicit).

#Response: #SuccessResponse | #ErrorResponse

#SuccessResponse: close({
	id:         string & !=""
	status:     "ok"
	outputs:    {[string]: _}
	decisions?: [...#Decision]
	warnings?:  [...#WireWarning]
})

#ErrorResponse: close({
	id:     string & !=""
	status: "error"
	// Free-form error message. op_runner.py:68 sends
	// traceback.format_exc() here; tests use plain strings like
	// "boom" (port_test.exs:60). Schema admits any non-empty string.
	error: string & !=""
})

// ─── Decision payload on the wire ──────────────────────────────────
//
// Decisions are free-form maps emitted by ops. The runtime's
// Decision.Store appends node_id + op_id + op_version + recorded_at
// server-side at record time (matches OPSPEC's #OpResult.decisions
// shape). The wire-protocol schema only requires that each decision
// is an object — its content fields are op-specific.
//
// Radar's claude_complete / radar_summarize ops (the reference
// implementation) emit a `decision_type` discriminator plus
// op-specific fields (model_id, prompt_hash, response_hash,
// token_usage). The schema does not lock those keys — packs choose
// their decision shape.

#Decision: {
	// Convention: every decision should carry a `decision_type`
	// discriminator string for downstream inspection. Not enforced
	// here (the schema admits decisions without it because
	// op_runner.py:74 forwards whatever the op returns) but every
	// Radar op today sets it.
	decision_type?: string
	...
}

// ─── Warning payload on the wire ───────────────────────────────────
//
// On the wire the warning is the JSON form produced by
// `warning_payload/1` (run.ex:710 / run/server.ex:1192). That helper
// stringifies atom keys and atom values, including severity. So:
//
//   - keys are strings ("code", "severity", ...) — not :code, etc.
//   - severity is the stringified atom ("degraded" not :degraded).
//
// This is the post-M-WARN-04 shape. The pre-fix shape (atom-keyed
// JSON) is rejected by an invalid fixture in this cohort —
// invalid/warning-atom-keyed.yaml — to make the legacy form's
// rejection explicit.

#WireSeverity: "info" | "low" | "medium" | "high" | "degraded"

#WireWarning: close({
	code:              string & !=""
	severity:          #WireSeverity
	summary:           string & !=""
	cause?:            string | null
	remediation?:      string | null
	affected_outputs?: [...string]
})

// Top-level: every YAML fixture under fixtures/v1.0.0/ unifies with
// #Exchange. close() on each variant rejects fixtures with stray
// top-level or in-shape keys.
#Exchange
