#!/usr/bin/env bash
# AI Framework v2 — Project Setup
# Generates platform adapter files so Copilot, Claude, and Codex can find the framework.
# Run from workspace root: bash .ai/setup.sh
# Safe to re-run — overwrites generated files, preserves .ai-repo/ content.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
WORKSPACE_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

# Colors (if terminal supports them)
if [[ -t 1 ]]; then
    GREEN='\033[0;32m'
    YELLOW='\033[1;33m'
    BLUE='\033[0;34m'
    NC='\033[0m'
else
    GREEN='' YELLOW='' BLUE='' NC=''
fi

log() { echo -e "${GREEN}✓${NC} $1"; }
info() { echo -e "${BLUE}ℹ${NC} $1"; }
warn() { echo -e "${YELLOW}⚠${NC} $1"; }

cd "$WORKSPACE_ROOT"

echo ""
echo "AI Framework v2 — Setup"
echo "========================"
echo ""

# Verify framework files exist
AI_DIR=".ai"
if [[ ! -f "$AI_DIR/rules.md" ]]; then
    echo "Error: Cannot find $AI_DIR/rules.md — is the framework installed?"
    exit 1
fi

info "Using framework from: $AI_DIR"

# ──────────────────────────────────────────────
# 0. Detect project-specific extensions (.ai-repo/)
# ──────────────────────────────────────────────
REPO_DIR=".ai-repo"
HAS_REPO_SKILLS=false
HAS_REPO_RULES=false

if [[ -d "$REPO_DIR/skills" ]] && compgen -G "$REPO_DIR/skills/*.md" >/dev/null 2>&1; then
    HAS_REPO_SKILLS=true
    info "Found project-specific skills in $REPO_DIR/skills/"
fi
if [[ -d "$REPO_DIR/rules" ]] && compgen -G "$REPO_DIR/rules/*.md" >/dev/null 2>&1; then
    HAS_REPO_RULES=true
    info "Found project-specific rules in $REPO_DIR/rules/"
fi

# ──────────────────────────────────────────────
# 1. GitHub Copilot + Claude Code — .github/ & .claude/
# ──────────────────────────────────────────────
info "Syncing Copilot agents/skills and Claude rules..."

# Clean slate for first-time setup (subsequent runs rely on sync.sh's incremental logic)
for dir in .github/agents .github/skills .claude/agents .claude/rules; do
    if [[ -d "$dir" ]]; then
        rm -rf "$dir"
        log "Removed old $dir/ (clean slate)"
    fi
done

# sync.sh handles everything:
#   .github/agents/   — framework stubs + repo-specific overrides
#   .github/skills/   — framework skills + repo-specific skills
#   .github/rules/    — repo-specific rules
#   .github/copilot-instructions.md — auto-generated entry point
#   .claude/rules/ai-framework.md   — pointer to .ai/ framework
bash "$SCRIPT_DIR/sync.sh"
log "Copilot and Claude synced via sync.sh"

# ──────────────────────────────────────────────
# 2. Codex — .codex/
# ──────────────────────────────────────────────
info "Setting up Codex..."

mkdir -p .codex

cat > .codex/instructions.md << 'CODEX_EOF'
# AI Framework v2
<!-- AUTO-GENERATED by .ai/setup.sh — do not edit manually -->

Read and follow:
1. `.ai/rules.md` — Non-negotiable guardrails
2. `.ai/paths.md` — Where artifacts live

Agents: `.ai/agents/` (planner, builder, reviewer, deployer)
Skills: `.ai/skills/` (plan-epic, plan-milestones, draft-spec, start-milestone, tdd-cycle, review-code, wrap-milestone, release)
Templates: `.ai/templates/` (epic-spec, milestone-spec, tracking-doc)

Key rules:
- Never commit without explicit human approval
- TDD by default: write tests first
- Follow Conventional Commits format
CODEX_EOF
log "Created .codex/instructions.md"

# ──────────────────────────────────────────────
# 3. Scaffold .ai-repo/ (project-specific extensions)
# ──────────────────────────────────────────────
info "Ensuring .ai-repo/ structure exists..."

mkdir -p .ai-repo/skills .ai-repo/rules

if [[ ! -f .ai-repo/README.md ]]; then
    cat > .ai-repo/README.md << 'REPO_README_EOF'
# Project-Specific AI Configuration

This directory holds AI framework extensions specific to **this repository**.
The shared framework lives in `.ai/` (submodule). This directory is repo-local.

## Structure

```
.ai-repo/
├── skills/    ← project-specific skill checklists
├── rules/     ← project-specific conventions and constraints
└── README.md  ← you are here
```

## Skills

Add a `.md` file in `skills/` with a checklist format (see `.ai/skills/` for examples).
Project skills are automatically picked up by `bash .ai/setup.sh` and distributed
to platform adapters (Copilot, Claude, Codex).

Examples of project-specific skills:
- `deploy-to-azure.md` — deployment runbook for this project
- `run-pipeline.md` — how to trigger the CI/CD pipeline
- `data-export.md` — how to export fixture data from production

## Rules

Add a `.md` file in `rules/` for project-specific conventions:
- `tech-stack.md` — "Use xUnit, NSubstitute, .NET 9"
- `naming.md` — "Services use I{Name} interface pattern"
- `testing.md` — "All tests use [Theory] for parameterized cases"

These are referenced by platform adapters so the AI reads them automatically.
REPO_README_EOF
    log "Created .ai-repo/README.md"
fi

log ".ai-repo/ structure ready"

# ──────────────────────────────────────────────
# 4. Create work directory structure
# ──────────────────────────────────────────────
info "Ensuring work directories exist..."

mkdir -p work/epics work/milestones/tracking work/releases
[[ -f work/gaps.md ]] || echo "# Gaps\n\nDiscovered work items deferred for later.\n" > work/gaps.md

log "Work directory structure ready"

# ──────────────────────────────────────────────
# 5. Create .gitignore entries if needed
# ──────────────────────────────────────────────
# No gitignore changes needed — all generated files should be committed

# ──────────────────────────────────────────────
# Summary
# ──────────────────────────────────────────────
echo ""
echo "========================"
echo "Setup complete!"
echo ""
echo "Generated platform adapters:"
echo "  .github/copilot-instructions.md  (GitHub Copilot)"
echo "  .github/agents/*.agent.md        (Copilot agents)"
echo "  .github/skills/*/SKILL.md        (Copilot skill references)"
echo "  .claude/rules/ai-framework.md    (Claude Code)"
echo "  .codex/instructions.md           (Codex)"
echo ""
echo "Project-specific extensions:"
echo "  .ai-repo/skills/    ← add project skills here"
echo "  .ai-repo/rules/     ← add project rules here"
echo ""
echo "To sync after changes:     bash .ai/sync.sh"
echo "To re-scaffold from scratch: bash .ai/setup.sh"
echo ""
echo "Get started:"
echo "  Copilot → @planner 'Plan feature X'"
echo "  Claude  → 'Act as planner. Plan feature X'"
echo ""
